name: "Build NixOS Configurations"
on:
  push:
    branches: [main]
    paths:
      - 'flake.lock'
  workflow_dispatch:

jobs:
  build-nixos:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hostname: [ "deck" ] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Free up to 130GB of space for the Nix store
        uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sk4g
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build System
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel