name: "Build NixOS Configurations"
on:
  workflow_run:
    workflows: ["Update flake.lock"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  build-nixos:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.head_commit.message == 'chore(flake): auto-update flake.lock'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hostname: [ "deck" ] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: sk4g
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build System
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel